Update README.md
In Anaconda Prompt (Anaconda3-2022.10-Windows-x86_64) on latest Windows 11, the last line in installation instruction fails with message at bottom.  Using double quotes instead of single quotes around git URL allows the command to execute without error.

ERROR: Invalid requirement: "'git+https://github.com/NVIDIA/apex.git'"